`timescale 1ns / 1ps
`ifndef DEFINTIONS_V
`define DEFINTIONS_V

`define BLOCK_SIZE 0
`define BLOCK_COUNT 1
`define ARGUMENT 2
`define TRANSFER_MODE 3
`define COMMAND 4
`define RESPONSE 5
`define PRESENT_STATE 6
`define TIMEOUT_CONTROL 7
`define SOFTWARE_RESET 8
`define NORMAL_INTERRUPT_STATUS 9
`define ERROR_INTERRUPT_STATUS 10
`define NORMAL_INTERRUPT_STATUS_ENABLE 11
`define ERROR_INTERRUPT_STATUS_ENABLE 12
`define NORMAL_INTERRUPT_SIGNAL_ENABLE 13
`define ERROR_INTERRUPT_SIGNAL_ENABLE 14
`define HOST_CONTROLLER_VERSION 15

`endif
