`timescale 1ns / 1ps
`ifndef DEFINTIONS_V
`define DEFINTIONS_V
	
`define HALF_PERIOD_SD 20
`define HALF_PERIOD 5
`define RESET_FIRE_TIME 100
`define RESET_DEACTIVATE_TIME 250
`define NEW_CMD_REQUEST_TIME 1000
`define SERIAL_READY_TIME 1300
`define STROBE_IN_TIME 2000
`define ACK_IN_TIME 2300

`endif

